# Dockerfile.worker
FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1-mesa-dev

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY ./src ./src
COPY ./config ./config
COPY .env .
COPY worker.py .

#CMD ["celery", "-A", "worker.celery_app", "worker", "-Q","","--loglevel=info"]

CMD celery -A worker.celery_app worker  -Q ${TASK_QUEUE} --loglevel=info