apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[your-index-name-*]" # Replace with your Elasticsearch index pattern
    jsonData:
      esVersion: 8.0.0
      timeField: "timestamp"