project_version: 0.1.0
logger_type: elasticsearch

ml_config_path: config/ml_config.yaml

# available model types
ml_model_types:
  - text_embedding
  #- style_transfer

# style transfer models, key and id
ml_models:
  # text_embedding models, key and id
  text_embedding:
    10: small
    11: base
    #large: 12

  # style_transfer:
  #   candy: 0
  #   mosaic: 1
  #   rain_princess: 2
  #   udnie: 3
  
  
# elasticsearch configuration for logging
elasticsearch_host: localhost
elasticsearch_port: 9200
elasticsearch_user: elastic
elasticsearch_password: changeme
elasticsearch_verify_certs: false

redis_host: localhost
rabbitmq_host: localhost