ML_CONFIG_PATH: config/ml_config.yaml

# Available model types
ML_MODEL_TYPES:
  - style_transfer

# Style transfer models mapping
ML_MODELS:
  style_transfer:
    candy: 0
    mosaic: 1
    rain_princess: 2
    udnie: 3


  