models:
  
  # Mevcut style transfer modelleri (bunları koruyabilir veya kaldırabilirsiniz)


  # Text Embedding Modelleri - Yeni eklenen
  small:
    name: "L6-v2"
    path: "models/all-MiniLM-L6-v2-onnx"
    framework: "onnx"
    version: "1.0.0"
    model_id: "10"
    description: "A large language model trained on a variety of internet text."
    params:
      onnx_file: "model.onnx"
      max_seq_length: 96
      batch_size: 32
      normalize: true
      embedding_dim: 384

  base:
    name: "mpnet-base-v2"
    path: "models/all-MiniLM-L12-v2-onnx"
    framework: "onnx"
    version: "1.0.0"
    model_id: "11"
    description: "A large language model trained on a variety of internet text."
    params:
      onnx_file: "model.onnx"
      max_seq_length: 384
      batch_size: 16
      normalize: true
      embedding_dim: 768
  
  # large:
  #   name: "roberta-large-v1"
  #   path: "models"
  #   framework: "onnx"
  #   version: "1.0.0"
  #   model_id: "12"
  #   params:
  #     onnx_file: "all-roberta-large-v1.onnx"
  #     max_seq_length: 512
  #     batch_size: 8
  #     normalize: true
  #     embedding_dim: 1024



  # candy_v1:
  #   name: "candy"
  #   path: "models/candy-8.onnx"
  #   framework: "onnx"
  #   version: "1.0.0"
  #   model_id: "0"
  #   params:
  #     input_shape: [1, 3, 224, 224]

  # mosaic_v1:
  #   name: "mosaic"
  #   path: "models/mosaic-9.onnx"
  #   framework: "onnx"
  #   version: "1.0.0"
  #   model_id: "1"
  #   params:
  #     input_shape: [1, 3, 224, 224]
  
  # rain_princess_v1:
  #   name: "rain_princess"
  #   path: "models/rain-princess-9.onnx"
  #   framework: "onnx"
  #   version: "1.0.0"
  #   model_id: "2"
  #   params:
  #     input_shape: [1, 3, 224, 224]