default_model: "model_v1"
models:
  model_A:
    v1:
      name: "style_transfer"
      version: "1.0.0"
      framework: "onnx"
      path: "models/style_v1.onnx"
      input_shape: [1, 3, 224, 224]
      input_type: "float32"
      device: "cuda"
      batch_size: 1
      options:
        optimize_memory: true
        enable_dynamic_shapes: false
    
    # v2:
    #   name: "style_transfer"
    #   version: "2.0.0"
    #   framework: "onnx"
    #   path: "models/style_v2.onnx"
    #   input_shape: [1, 3, 512, 512]
    #   device: "cuda"
    #   options:
    #     optimize_memory: true


  model_B:
    v1:
      name: "style_transfer"
      version: "1.0.0"
      framework: "onnx"
      path: "models/style_v1.onnx"
      input_shape: [1, 3, 224, 224]
      input_type: "float32"
      device: "cuda"
      batch_size: 1
      options:
        optimize_memory: true
        enable_dynamic_shapes: false
    
    # v2:
    #   name: "style_transfer"
    #   version: "2.0.0"
    #   framework: "onnx"
    #   path: "models/style_v2.onnx"
    #   input_shape: [1, 3, 512, 512]
    #   device: "cuda"
    #   options:
    #     optimize_memory: true


  preprocessing:
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  resize:
    method: "bilinear"
    
postprocessing:
  denormalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

cache_ttl: 3600
max_batch_size: 32
allowed_formats: ["jpg", "png", "jpeg"]